version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: gubee
      POSTGRES_PASSWORD: gubee
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - db